In [1]:
import numpy as np
import pandas as pd

#### 1. Create a 6x3 integer array with values ranging from 10 to 100 such that the difference between each element is 5

In [2]:
task1 = np.array([[10, 15, 20],
                 [15, 20, 25],
                 [20, 25, 30],
                 [25, 30, 35],
                 [30, 35, 40],
                 [35, 40, 45]])
                

In [3]:
print(task1)

[[10 15 20]
 [15 20 25]
 [20 25 30]
 [25 30 35]
 [30 35 40]
 [35 40 45]]


#### 2. Create a numpy array using only starting point, length, and step

In [4]:
length, start, step = 15, 15, 5

In [5]:
task2 = np.arange(15, 85, 5)

In [6]:
print(task2)

[15 20 25 30 35 40 45 50 55 60 65 70 75 80]


#### 3. Find the index of 3rd repetition of number 2 in my_array

In [7]:
my_array = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [8]:
result = np.where(my_array == 2)
print(result[0][2])

12


#### 4. Subtract the one_dim from the two_dim, such that each item of one_dim is subtracted from respective row of two_dim

In [9]:
two_dim = np.array([[30,30,30], [40,40,40], [50,50,50]])
one_dim = np.array([10,20,30])

In [10]:
print(two_dim - one_dim)

[[20 10  0]
 [30 20 10]
 [40 30 20]]


#### 5. Drop all nan values from my_array

In [11]:
my_array = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [12]:
my_array = my_array[~np.isnan(my_array)]
print(my_array)

[1. 2. 3. 5. 6. 7.]


#### 6. Find the mode of petal length (column No 3) in iris dataset

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='object')

In [14]:
from scipy import stats
petal = data[:, 2]
print('mode:', stats.mode(petal)[0],\
      'count: ', stats.mode(petal)[1])

mode: [b'1.5'] count:  [14]


#### 7. Normalize sepal length (column No 1) values so that they are exactly between 0 and 1

In [15]:
sepal = data[:, 0]
sepal = sepal.astype('float')
min = sepal.min()
max = sepal.max()
sepal = (sepal - min)/(max - min)
print(sepal)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

#### 8. Get the positions of top 5 maximum values in my_array

In [16]:
np.random.seed(100)
my_array = np.random.uniform(1, 50, 20)

In [17]:
print(my_array)
sorted_array = my_array.argsort()
print(sorted_array[:5])

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[ 4 13  5  8 17]


#### 9. Replace all values greater than 50 with 50 and less than 0 to 0 in my_array

In [18]:
np.random.seed(100)
my_array = np.random.uniform(-10,100, 30)

In [19]:
print(my_array)
my_array[my_array>50] = 50
my_array[my_array<0] = 0
print(my_array)


[49.7745436  20.62063236 36.69693498 82.92537456 -9.48092582  3.37260329
 63.78239932 80.84380306  5.03772487 53.26026624 88.04541497 13.01223343
 10.38610415  1.92145795 14.16672419 97.64861632 79.2851464   8.9135114
 79.78472236 20.14811217 37.4874602  93.40328016 79.94143167 26.97231451
  9.29514991 31.01152509 -9.37426419 17.76689888 77.52287593 -8.32195316]
[49.7745436  20.62063236 36.69693498 50.          0.          3.37260329
 50.         50.          5.03772487 50.         50.         13.01223343
 10.38610415  1.92145795 14.16672419 50.         50.          8.9135114
 50.         20.14811217 37.4874602  50.         50.         26.97231451
  9.29514991 31.01152509  0.         17.76689888 50.          0.        ]


#### 10. Read every 10th row and only specified columns of Boston Housing dataset as a dataframe, convert 'chas' column name to 'river', and write the output to an Excel file without index

In [20]:
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
columns = ['crim', 'chas', 'nox', 'tax', 'ptratio', 'medv']

In [35]:
save = pd.read_csv(url)
print(save.columns)
df = pd.read_csv(url, usecols = columns)
df = df.iloc[::10, :]
#or..
#df = df[df.index%10 == 0])
df = df.rename(columns = {'chas':'river'})
print(df)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
         crim  river     nox  tax  ptratio  medv
0     0.00632      0  0.5380  296     15.3  24.0
10    0.22489      0  0.5240  311     15.2  15.0
20    1.25179      0  0.5380  307     21.0  13.6
30    1.13081      0  0.5380  307     21.0  12.7
40    0.03359      0  0.4280  252     18.3  34.9
50    0.08873      0  0.4390  243     16.8  19.7
60    0.14932      0  0.4530  284     19.7  18.7
70    0.08826      0  0.4130  305     19.2  24.2
80    0.04113      0  0.4260  281     19.0  28.0
90    0.04684      0  0.4890  270     17.8  22.6
100   0.14866      0  0.5200  384     20.9  27.5
110   0.10793      0  0.5200  384     20.9  21.7
120   0.06899      0  0.5810  188     19.1  22.0
130   0.34006      0  0.6240  437     21.2  19.2
140   0.29090      0  0.6240  437     21.2  14.0
150   1.65660      0  0.8710  403     14.7  21.5
160   1.27346      1  0.6

#### 11. Which decade was the most dangerous to live in the US according to crime rates data?

In [98]:
df = pd.read_csv('US_Crime_Rates_1960_2014.csv')
df['Year'] = df['Year'].apply(lambda x: (x//10)*10)
columns = df.columns
df = df.groupby('Year').agg(avg_crimes = ('Total', 'mean'), \
                            avg_pop = ('Population', 'mean'))
df['danger'] = df['avg_crimes']/df['avg_pop']
print(df[df['danger']==df['danger'].max()])

      avg_crimes      avg_pop    danger
Year                                   
1980  13112336.9  237137006.9  0.055294


#### 12. Drop the rows from the movies dataset where all elements are missing. Was there any?

In [103]:
df = pd.read_csv('movies_metadata.csv')
df.dropna(how = 'all', inplace = True)
print(df)

#No

    adult                              belongs_to_collection    budget  \
0   False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1   False                                                NaN  65000000   
2   False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3   False                                                NaN  16000000   
4   False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
5   False                                                NaN  60000000   
6   False                                                NaN  58000000   
7   False                                                NaN         0   
8   False                                                NaN  35000000   
9   False  {'id': 645, 'name': 'James Bond Collection', '...  58000000   
10  False                                                NaN  62000000   
11  False                                                NaN         0   
12  False  {'id': 117693, 'name': 'Bal

#### 13. Merge df1 and df2 to get df3

In [24]:
df1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K1'],
                    'P': ['P0', 'P1', 'P2', 'P3'],
                    'Q': ['Q0', 'Q1', 'Q2', 'Q3']}) 
df2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                    'key2': ['K0', 'K0', 'K0', 'K0'],
                    'R': ['R0', 'R1', 'R2', 'R3'],
                    'S': ['S0', 'S1', 'S2', 'S3']})
df3 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K1', 'K2', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K0', 'K1', 'K0'],
                    'P': ['P0', 'P1', 'P2', 'P2', 'P3', np.nan],
                    'Q': ['Q0', 'Q1', 'Q2', 'Q2', 'Q3', np.nan],
                    'R': ['R0', np.nan, 'R1', 'R2', np.nan, 'R3'],
                    'S': ['S0', np.nan, 'S1', 'S2', np.nan, 'S3']})
print("Original DataFrames:\nDataframe 1:\n", df1, '\nDataFrame 2:\n', df2)
print("Desired DataFrame:\n", df3)

Original DataFrames:
Dataframe 1:
   key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3 
DataFrame 2:
   key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3
Desired DataFrame:
   key1 key2    P    Q    R    S
0   K0   K0   P0   Q0   R0   S0
1   K0   K1   P1   Q1  NaN  NaN
2   K1   K0   P2   Q2   R1   S1
3   K1   K0   P2   Q2   R2   S2
4   K2   K1   P3   Q3  NaN  NaN
5   K2   K0  NaN  NaN   R3   S3


In [25]:
df3 = pd.merge(df1, df2, how = 'outer')
print(df3)

  key1 key2    P    Q    R    S
0   K0   K0   P0   Q0   R0   S0
1   K0   K1   P1   Q1  NaN  NaN
2   K1   K0   P2   Q2   R1   S1
3   K1   K0   P2   Q2   R2   S2
4   K2   K1   P3   Q3  NaN  NaN
5   K2   K0  NaN  NaN   R3   S3


#### 14. Merge left_df and right_df to get df

In [26]:
left_df = pd.DataFrame({'transaction_id': ['A', 'B', 'C', 'D'], 
                       'user_id': ['Peter', 'John', 'John', 'Anna'],
                       'value': [43, 76, 54, 88]})
right_df = pd.DataFrame({'user_id_r': ['Paul', 'Mary', 'John', 'Anna', 'Edward'],
                        'favorite_color': ['blue', 'blue', 'red', np.nan, 'orange']})
df = pd.DataFrame({'transaction_id': ['A', 'B', 'C', 'D'],
                   'user_id': ['Peter', 'John', 'John', 'Anna'],
                   'value': [43, 76, 54, 88],
                   'favorite_color': ['blue', 'blue', 'red', np.nan]})
print("Original DataFrames:\nDataframe 1:\n", left_df, '\nDataFrame 2:\n', right_df)
print("Desired DataFrame:\n", df)

Original DataFrames:
Dataframe 1:
   transaction_id user_id  value
0              A   Peter     43
1              B    John     76
2              C    John     54
3              D    Anna     88 
DataFrame 2:
   user_id_r favorite_color
0      Paul           blue
1      Mary           blue
2      John            red
3      Anna            NaN
4    Edward         orange
Desired DataFrame:
   transaction_id user_id  value favorite_color
0              A   Peter     43           blue
1              B    John     76           blue
2              C    John     54            red
3              D    Anna     88            NaN


In [27]:
df = left_df.join(right_df)
print(df)

# understanding between join, merge, on, right, left, outer

  transaction_id user_id  value user_id_r favorite_color
0              A   Peter     43      Paul           blue
1              B    John     76      Mary           blue
2              C    John     54      John            red
3              D    Anna     88      Anna            NaN


#### 15.  Convert year and day of year into a single date column to get the desired DataFrame 

In [28]:
data1 = pd.DataFrame({"year": [2005, 2008, 2010, 2022],
                      "day_of_the_year": [250, 364, 1, 176]})
data2 = pd.DataFrame({"year": [2005, 2008, 2010, 2022],
                      "day_of_the_year": [250, 364, 1, 176],
                      "date": ['2005-09-07', '2008-12-29', '2010-01-01', '2022-06-25']})
print("Original DataFrame:\n", data1)
print("Desired DataFrame:\n", data2)

Original DataFrame:
    year  day_of_the_year
0  2005              250
1  2008              364
2  2010                1
3  2022              176
Desired DataFrame:
    year  day_of_the_year        date
0  2005              250  2005-09-07
1  2008              364  2008-12-29
2  2010                1  2010-01-01
3  2022              176  2022-06-25


In [130]:
def date(year, day):
    months = {'1':31, '2':28, '3':31, '4':30, '5':31, '6':30, \
              '7':31, '8':31, '9':30, '10': 31, '11':30, '12':31 }
    for key in months:
        i = 0
        if year.iloc[i] % 4 == 0:
            months.update({'2': 29})
        else:
            months.update({'2': 29})
        l = 0
        l += months[key]
        if l >= day[i]:
            break
    l -= months[key]
    month = key
    number = str(day[i] - l)
    i += 1
    return "{}-{}-{}".format(year[i], month, number)


In [131]:
lk = date(data1['year'], data1['day_of_the_year'])

In [132]:
print(lk)

2008-12-250
